# Generated by Django 6.0.6 on 2026-07-09 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=150, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('client_contact', models.IntegerField()),
                ('client_password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(12, 'Password length should be at least 12 ccharacters')])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.DateTimeField()),
                ('client_email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myBackend.clientdetails')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myBackend.service')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFreeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_day', models.DateField()),
                ('free_time', models.DateTimeField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myBackend.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_status', models.CharField(max_length=100)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myBackend.appointment')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myBackend.employeefreeslot')),
            ],
        ),
    ]
