# Generated by Django 6.0.6 on 2026-07-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='client_password',
            field=models.CharField(max_length=150),
        ),
    ]
