# Generated by Django 6.0.6 on 2026-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackend', '0003_services_alter_appointment_service_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_price',
            field=models.CharField(max_length=100),
        ),
    ]
