# Generated by Django 6.0.6 on 2026-07-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackend', '0004_alter_services_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_des',
            field=models.CharField(max_length=600),
        ),
    ]
